### ISSUE TITLE
Add more information on getting Python 2 versions of images

### ISSUE THREAD

**Issue by pgleeson** [NeuralEnsemble/neuralensemble-docker#3]
Currently the DockerHub entries you get when you pull:

```
 docker pull neuralensemble/simulationx
```

are those built for Python 3. It would be good to be able to pull the Python 2 versions, which would probably be more widely used. This would require creating https://hub.docker.com/r/neuralensemble/base_py2 etc.

**Comment by apdavison** [comment]
The Python 2 versions are already there. To get them, use the "py2" tag, e.g.:

```
docker pull neuralensemble/simulationx:py2
```

This information is given in this [blog post](http://neuralensemble.blogspot.fr/2016/05/updated-docker-images-for-biological.html) but I guess it would be good to add it to the README and to the DockerHub description, so I'll leave this ticket open until that's done.

**Comment by pgleeson** [comment]
Thanks for clearing that up. All works fine for me now!

Have updated the title of the issue to reflect your comment

**Comment by pgleeson** [comment]
Seems to be clear in Readmes...
