### ISSUE TITLE
Update Dockerfiles for PyNN 0.9.4 and make new release on Dockerhub

### ISSUE THREAD

**Issue by pgleeson** [NeuralEnsemble/neuralensemble-docker#9]
@apdavison I'm keen to get an updated set of Docker files for the latest version of PyNN. Have started testing this here: https://github.com/pgleeson/neuralensemble-docker/tree/test_pynn094_py2

Some questions:
1) It would be good to use an updated base image (one of these: https://hub.docker.com/_/neurodebian). Is there any reason to go with Debian (e.g. 9.0, stretch)? I've successfully tested with neurodebian:xenial (Ubuntu 16.04) which might be more widespread and is available as an environment on Travis.
2) There was an attempt to update to Neuron 7.5 which was reverted. Anything insurmountable, and should I aim for Neuron 7.6?
3) Which version of Neo is required/preferred?

**Comment by apdavison** [comment]
I have a memory that I updated the Python 2 branch a few months ago, but I didn't push it to Github because I wanted to update Python 3 as well. This must have been on my old laptop, though, so I'll need a day or two to track it down.

Answers:
1. agree, neurodebian:xenial sounds good
2. I don't remember what the problem was; worth trying 7.6
3. the latest (0.7.x)

**Comment by apdavison** [comment]
ok, I pushed the work I did a few months ago, you can see the changes here: https://github.com/NeuralEnsemble/neuralensemble-docker/compare/python2...stretch-py2

If you're happy to work on this update, I don't propose to merge those changes, but they might be of some help, in particular the need to add the zlib1g-dev package to the base image.

**Comment by pgleeson** [comment]
Thanks. Re Neo, the PyNNTextIO has been removed in 0.7.1 (intentionally: https://github.com/NeuralEnsemble/python-neo/issues/469), but it's handy writing voltages to plain text files for comparing with nml (and it's used in Potjans/Diesmann https://github.com/NeuralEnsemble/PyNN/blob/master/examples/Potjans2014/microcircuit.py#L13). Any preferred equivalent/similar write format?

**Comment by apdavison** [comment]
Yes, AsciiSignalIO should do the job. This was recently extended to support an accompanying JSON file containing metadata such as the sampling rate.

**Comment by pgleeson** [comment]
FYI @apdavison making good progress with this, but it's closely related to a bigger set of changes for testing all OSB models with the latest versions of simulators (and checking python3 compatibility)...

**Comment by pgleeson** [comment]
@apdavison I have working python2 (here: https://github.com/pgleeson/neuralensemble-docker/tree/test_pynn094_py2) and python3 (here: https://github.com/pgleeson/neuralensemble-docker/tree/test_pynn094) based Docker files for:
PyNN v0.9.4
NEURON  v7.6.7
NEST v2.16.0.

I see though you have a PyNN 0.9.5 release. Would it be useful to do a PR with the above files, tag a release and then test for 0.9.5? What NRN/NEST versions are supported there?

**Comment by apdavison** [comment]
@pgleeson yes, that would be helpful. PyNN 0.9.5 supports NEST v2.18.0 (and a broad range of NEURON versions).

**Comment by pgleeson** [comment]
Ok, @apdavison , I've opened 2 PRs. If you're happy with them, the updates for 0.9.5 should be easy.

**Comment by pgleeson** [comment]
Out of date...
